### ISSUE TITLE
WSL2 - RuntimeError: Failed to compile helper

### ISSUE THREAD

**Issue by steponmepls** [Soreepeong/XivMitmLatencyMitigator#64]
I [recently](https://techcommunity.microsoft.com/t5/windows-10/wsl2-network-routes/m-p/1402469/highlight/true#M3668) found out WSL2, unlike WSL1, gets its "own nic, and IP address behind an internal switch (172.25.168.87)".
I wanted to give it a try and see if I could make the script run without a VM but after solving a python incompatibility issue (by default wsl debian only comes with python3.5 so I had to [compile](https://computingforgeeks.com/how-to-install-python-on-debian-linux/) python3.10 myself), I bumped into this error when trying to compile the oodle helper:
```bash
user@DESKTOP-QUJDQGV:~/xivalexander$ python3.10 ./mitigate.py
2022-10-07 00:02:47,044 17861(main)     INFO    Region filter: (None)
2022-10-07 00:02:47,044 17861(main)     INFO    Extra delay: 0.075s
2022-10-07 00:02:47,044 17861(main)     INFO    Use measured socket latency: no
g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++03’?
Traceback (most recent call last):
  File "/home/user/xivalexander/./mitigate.py", line 1667, in <module>
    exit(__main__())
  File "/home/user/xivalexander/./mitigate.py", line 1557, in __main__
    OodleHelper.init_executable()
  File "/home/user/xivalexander/./mitigate.py", line 831, in init_executable
    raise RuntimeError("Failed to compile helper")
RuntimeError: Failed to compile helper
```
Is this also a version issue? Meaning I need updated `g++ gcc-multilib g++-multilib` libraries?

**Comment by steponmepls** [comment]
On a side note Ubuntu `20.04.5 LTS` comes with preinstalled python3.8 but with gcc 9 and `22.04.1 LTS` comes with preinstalled python3.10 and gcc 10. It is still possible to install gcc 10 in `20.04.5 LTS` but the same error displayed above will happen. The latter uses nftables over iptables so the syntax is quite different compared to what is described in the docs. I will try testing more with `22.04.1 LTS` in the meantime

**Comment by steponmepls** [comment]
`22.04.1 LTS` shows a series of warning but after [switching](https://wiki.debian.org/iptables) from `nftables` to legacy `iptables`, the script appears to be running without errors
```bash
user@DESKTOP-QUJDQGV:~/xivalex$ sudo su
root@DESKTOP-QUJDQGV:/home/user/xivalex# python3 ./mitigate.py
2022-10-07 00:52:08,490 3156(main)      INFO    Region filter: (None)
2022-10-07 00:52:08,490 3156(main)      INFO    Extra delay: 0.075s
2022-10-07 00:52:08,490 3156(main)      INFO    Use measured socket latency: no
/home/user/xivalex/./oodle_helper.cpp: In function ‘int main()’:
/home/user/xivalex/./oodle_helper.cpp:248:16: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  248 |         freopen(NULL, "rb", stdin);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/user/xivalex/./oodle_helper.cpp:249:16: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  249 |         freopen(NULL, "wb", stdout);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/user/xivalex/./oodle_helper.cpp:366:22: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  366 |                 fread(&hdr, sizeof(hdr), 1, stdin);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/xivalex/./oodle_helper.cpp:372:22: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  372 |                 fread(&src[0], 1, src.size(), stdin);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Base: 0xf3cf9000
Oodle encode test: 256 -> 100
Oodle helper running: state=2eb400 shared=400018 window=8000
```

**Comment by steponmepls** [comment]
The script doesn't react. I can ping from host to client but not the opposite so maybe that's why I can't connect through..
I also noticed that the IP from WSL ends with `/20` so maybe that's also an issue (ex: `172.31.55.134/20`)

![image](https://user-images.githubusercontent.com/63500907/194435668-92f77bc3-27d8-4e19-ba10-c441c6d697d9.png)

**Comment by steponmepls** [comment]
Looks like oodle helper compiles properly even on debian WSL if you switch to [testing](https://archive.ph/ADexm) and then install the required depndencies and [switch](https://wiki.debian.org/iptables) from nftables to iptables syntax:
```bash
# apt install build-essential g++ gcc-multilib g++-multilib curl python3 iptables
```
So the fact packets won't reach the script isn't caused by badly compiled dependencies after all and it would probably require its own issue. Closing this, I guess
