### ISSUE TITLE
6.35 broken again today.

### ISSUE THREAD

**Issue by bankjaneo** [Soreepeong/XivMitmLatencyMitigator#77]
Last night I was playing fine until today I find myself unable to log in to character selection screen with following errors. Does anyone happen to have successful login today?

**Error when using latest 6.35 ffxiv.exe**

```
bankja@igc-vps:~$ curl https://raw.githubusercontent.com/Soreepeong/XivMitmLatencyMitigator/main/mitigate.py | sudo python3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  121k  100  121k    0     0   273k      0 --:--:-- --:--:-- --:--:--  273k
2023-03-10 10:51:46,314 2853614(main)   INFO    Region filter: (None)
2023-03-10 10:51:46,315 2853614(main)   INFO    Extra delay: 0.075s
2023-03-10 10:51:46,315 2853614(main)   INFO    Use measured socket latency: no
/oodle_helper.cpp: In function ‘int main()’:
/oodle_helper.cpp:462:16: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  462 |         freopen(NULL, "rb", stdin);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~
/oodle_helper.cpp:463:16: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  463 |         freopen(NULL, "wb", stdout);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~
/oodle_helper.cpp:515:22: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  515 |                 fread(&oodleXiv, sizeof oodleXiv, 1, fprev);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/oodle_helper.cpp:575:22: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  575 |                 fread(&hdr, sizeof(hdr), 1, stdin);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/oodle_helper.cpp:580:22: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  580 |                 fread(&src[0], 1, src.size(), stdin);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Base: 0xF3C47000
All signatures resolved.
htbits: 0x11
window size: 0x100000
SharedSize: ffxiv.exe+0x1244700
SetMallocFree: ffxiv.exe+0x123B080
SharedSetWindow: ffxiv.exe+0x12445E0
UdpStateSize: ffxiv.exe+0x12432C0
TcpStateSize: ffxiv.exe+0x1242AA0
TcpTrain: ffxiv.exe+0x1242AB0
UdpTrain: ffxiv.exe+0x12435F0
TcpDecode: ffxiv.exe+0x1242A30
UdpDecode: ffxiv.exe+0x1242BE0
TcpEncode: ffxiv.exe+0x1242A50
UdpEncode: ffxiv.exe+0x1242C20
Oodle helper running.
2023-03-10 10:51:54,288 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 119.97.0.0/16 -j REDIRECT --to 32203
2023-03-10 10:51:54,292 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 153.254.80.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,295 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 109.244.0.0/16 -j REDIRECT --to 32203
2023-03-10 10:51:54,298 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 124.150.157.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,301 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 210.94.0.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,304 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 27.221.0.0/16 -j REDIRECT --to 32203
2023-03-10 10:51:54,307 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 183.111.189.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,309 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 202.67.52.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,312 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 80.239.145.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,315 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 204.2.229.0/24 -j REDIRECT --to 32203
2023-03-10 10:51:54,318 2853614(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 162.14.0.0/16 -j REDIRECT --to 32203
net.ipv4.ip_forward = 1
2023-03-10 10:51:54,323 2853614(main)   INFO    Listening on ('0.0.0.0', 32203)...
2023-03-10 10:51:54,323 2853614(main)   INFO    Press Ctrl+C to quit.
2023-03-10 10:52:15,799 2854521 INFO    Log will be saved to /tmp/xmlm.20230310105215.2854521.log
Traceback (most recent call last):
  File "<stdin>", line 3112, in <module>
  File "<stdin>", line 3078, in __main__
  File "<stdin>", line 2202, in __init__
NameError: name 'use_companion_program' is not defined
2023-03-10 10:52:15,830 2853614(main)   INFO    [2853822] has exit with status code 9.
```

**Error when using latest 6.35 ffxiv_dx11.exe**

```
bankja@igc-vps:~$ curl https://raw.githubusercontent.com/Soreepeong/XivMitmLatencyMitigator/main/mitigate.py | sudo python3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  121k  100  121k    0     0  1094k      0 --:--:-- --:--:-- --:--:-- 1105k
2023-03-10 10:53:25,048 2856409(main)   INFO    Region filter: (None)
2023-03-10 10:53:25,049 2856409(main)   INFO    Extra delay: 0.075s
2023-03-10 10:53:25,049 2856409(main)   INFO    Use measured socket latency: no
Not using companion program: Need ffxiv.exe in the same directory. Copy one from your local Windows/Mac installation.
2023-03-10 10:53:26,588 2856409(main)   INFO    Downloading opcode definition files...
2023-03-10 10:53:27,563 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 124.150.157.0/24 -j REDIRECT --to 15510
2023-03-10 10:53:27,566 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 109.244.0.0/16 -j REDIRECT --to 15510
2023-03-10 10:53:27,569 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 119.97.0.0/16 -j REDIRECT --to 15510
2023-03-10 10:53:27,571 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 210.94.0.0/24 -j REDIRECT --to 15510
2023-03-10 10:53:27,575 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 27.221.0.0/16 -j REDIRECT --to 15510
2023-03-10 10:53:27,579 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 202.67.52.0/24 -j REDIRECT --to 15510
2023-03-10 10:53:27,582 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1:65535 -d 162.14.0.0/16 -j REDIRECT --to 15510
2023-03-10 10:53:27,585 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 204.2.229.0/24 -j REDIRECT --to 15510
2023-03-10 10:53:27,589 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 153.254.80.0/24 -j REDIRECT --to 15510
2023-03-10 10:53:27,593 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 80.239.145.0/24 -j REDIRECT --to 15510
2023-03-10 10:53:27,596 2856409(main)   INFO    Running: iptables -t nat -I PREROUTING -p tcp -m multiport --dports 1025:65535 -d 183.111.189.0/24 -j REDIRECT --to 15510
net.ipv4.ip_forward = 1
2023-03-10 10:53:27,605 2856409(main)   INFO    Listening on ('0.0.0.0', 15510)...
2023-03-10 10:53:27,605 2856409(main)   INFO    Press Ctrl+C to quit.
2023-03-10 10:54:11,678 2857870 INFO    Log will be saved to /tmp/xmlm.20230310105411.2857870.log
Traceback (most recent call last):
  File "<stdin>", line 3112, in <module>
  File "<stdin>", line 3078, in __main__
  File "<stdin>", line 2202, in __init__
NameError: name 'use_companion_program' is not defined
2023-03-10 10:54:11,729 2856409(main)   INFO    [2857870] has exit with status code 256.
```

PS. For anyone that using my docker version, set the environment MITIGATOR=false for now to disable XivMitmLatencyMitigator script.

**Comment by Soreepeong** [comment]
Now that was a stupid mistake. It should work now! If it doesn't fetch the updated script for some reason, replace if/else at L2202 to `self.oodle = OodleHelper()`.

**Comment by bankjaneo** [comment]
It's working now. You're awesome! Thanks so much again.
